sudo: false
language: python
python:
- 3.4
cache:
  pip: true
  directories:
  - node_modules
install:
- npm install
- pip install -r requirements/development.txt
script:
- make pylint
- ./manage.py test
env:
  secure: jmXKz5c7zwr7apjJSqCkaOnDJ98X6WgL31uV/dQDoh6qweN74omk8wJYNzD9CqXZPfnNfD82zRphIaEJ0iiJ15C5aFcm2i1TgRp7mvNcl7OfsgJ91ZYKK89wWXTjlQ3XQunC9LHOLDIUSVHN/083DjXecBBfRW+55TwghpIb1pxrxDzhHV4gBVcgNuz/Ul5LacsDBF8Yw/xn4/sAgqCgKt7AWZwlXhWbgXjtJfu9EkLzwIWc0nRUyqaVcMWERsSHLJcVXKo0UFYO1haRr4iccRDDsutGzVqxEyOASzDv6KXwjvS6uE0r9VtPnLf/fNr+9FTaBfHN/ZspkhR9OcygS8Jzh9ZvEVsEBjLm4Mu60pyphjNEz+wwIZrEB6rJkvYs0e4q4hYNpjNWd2g8gG3lTrXwf1xH1bNyJ6TB3yUkkFrzO91xGDctqRsByKD5YxMo4OneW1oBkoblk2q9MVKbTXmDbcGFtn9SXfOetrmkXma3jlMwf/tXovcLmxnHW5eGu2FeAZpfejgPErab4UGSbpfFIzHfjsiMeFyFBIbRLgSUr4YZcDW2Bukv25VzSMUM7VSIlGs8IAKEIBbcme/ej3+keAgzw8Ki1d+iCmtY7HCyuFVkEhJgcVkmT90bstqa7NUkTllwPUAbRJCM/hodDzrjizfYWkbcTP/w6gBgmoQ=
