sudo: false
language: python
python:
- 3.4
cache:
  pip: true
  directories:
  - node_modules
install:
- npm install
- pip install -r requirements/development.txt
script:
- make pylint
- ./manage.py test
