sudo: false
language: python
python:
- 3.4
cache:
  directories:
  - node_modules
  - $HOME/.cache/pip
  - $HOME/todo_app/components
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- npm install
- pip install -r requirements/development.txt
- ./manage.py bower install
script:
- make pylint
- make flake8
- ./manage.py test
- make coverage
env:
  global:
    - DJANGO_SETTINGS_MODULE="todo_app.settings.development"
    - secure: agJvcBVpHXiV66WvkEod9nU3Kf7hQjE7bIdAnA9lWJHOLxguaJAPZy6SQAB6HIae+mtnloDrYySCWn0R0FqZz5r8lb2nmPnUuG5yDV1STsMhuEBYmAto4lctTpK/iSD9bzgf+im0dRCDwqV7TgDxesKQecXOaCDgkDm2YE2w1F0iVuGCeU+C/vZuxQ79qQqy5ZyxExKFHXo6JYUiFHUJv2bqNg/aw4oI4Hvhd/0lGKl0HjrXEd54EG75UTie9wbpLnoqpXbK5SE2zQ3YRyz7oFeMSFhfow9bV8lUthsWoDUhMKzsUwzaxVn68gG+0PNOWCU7hGlQ0MNNlHMkCw/k7T+nnbDrroY47Sc8MQzTvy4gCc3+Um6GpFR1X6UL15gL+kD3Ny73tlI8vd0m4uosz+c4gTHXTYFfboKJFLTv7VAeB4CDQpZO/FJmzi4bxvxouOpU7z/pwsPTfRReK4bvtqOpAo0lTLi/qOpQ3Nlxpi+UkDMoAYT7yfxiIr8RqXSb0NLJeuDuOyeM3+HG5toXE+PWRtnbb9hAxyV9wUeESDAru3zJI/ynsujasfKCQ2uggXajFTVBDQ5V5Amt+p9g+fr1VjnQ+ol0BkYqZoB86QeDgCJpISHaKBO+GAlgmCXH58fCsbczpSlHtPxiVpUGr9RIeI68AkF9HULB3Npgqgk=
